layout_spectrum: 0.3817204
typography_spectrum: 0.1129032
color:
  saturation: 0.2329749
  lightness: 0.2777778
  brandStrength: 0
  rhythmicContrast: 0.1039427
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: Wild Wild Wealth
