name: Wild Wild Wealth
favicon: null
layout_spectrum: 0.3817204
typography_spectrum: 0.7150537
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Your Wealth Guru for an Inspired Future
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0
  lightness: 0.1810036
  saturation: 0.7455197
  rhythmicContrast: 0.3172043
purpose: []
